### ISSUE TITLE
Open Source License?

### ISSUE THREAD

**Issue by major** [rclayton-the-terrible/Ansible-OpenSSL#3]
I'm very interested in some of the work you've done here, but I don't see a license within the repo or in any of the source files.  Have you considered an open source license, like Apache 2 or MIT, for your code?

**Comment by rclayton-the-terrible** [comment]
MIT.

**Comment by rclayton-the-terrible** [comment]
@major Just added the license.  I hope that unblocks you if you were prevented from doing something.

**Comment by major** [comment]
Awesome. Thanks so much! :)
